// AUTO-GENERATED by scripts/gen-video-manifest.py - do not edit by hand.
window.VIDEO_MANIFEST = {
  "rules": {
    "frida-puplo": [
      "images/videos/rules/frida-puplo/nohead.MP4"
    ],
    "k-pup": [],
    "lady-puppa": [],
    "pupquiao": [
      "images/videos/rules/pupquiao/nopointing1.MP4",
      "images/videos/rules/pupquiao/nopointing2.mp4",
      "images/videos/rules/pupquiao/nopointing3.mp4"
    ],
    "pupstein": [
      "images/videos/rules/pupstein/bark1.MP4",
      "images/videos/rules/pupstein/bark2.MP4",
      "images/videos/rules/pupstein/bark3.mp4",
      "images/videos/rules/pupstein/bark4.mp4"
    ],
    "queen-elizapup": [],
    "rupup": [
      "images/videos/rules/rupup/dontsayi.MP4",
      "images/videos/rules/rupup/dontsayi2.MP4",
      "images/videos/rules/rupup/dontsayi3.mp4",
      "images/videos/rules/rupup/dontsayi4.mp4"
    ]
  },
  "steal": [
    "images/videos/steal/steal1.MP4",
    "images/videos/steal/steal2.MP4"
  ],
  "block": [
    "images/videos/block/block1.mp4"
  ],
  "general": [
    "images/videos/general/general1.MP4",
    "images/videos/general/general2.mp4"
  ]
};
