#!/usr/bin/env python3
"""Generate images/videos/manifest.js listing the video files in each folder.

The site loads this file to know which clips exist per rule/steal/block, so
videos can be added just by dropping them in a folder — no code edits.

Auto-run by scripts/compress-videos.sh (and thus the GitHub Action).
Do NOT edit manifest.js by hand.

Usage: python3 gen-video-manifest.py [ROOT]   (default ROOT: images/videos)
"""
import json
import os
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else "images/videos"
VIDEO_EXTS = {".mp4", ".mov", ".m4v", ".webm"}


def list_videos(directory):
    if not os.path.isdir(directory):
        return []
    files = []
    for name in sorted(os.listdir(directory)):
        path = os.path.join(directory, name)
        if os.path.isfile(path) and os.path.splitext(name)[1].lower() in VIDEO_EXTS:
            files.append(path.replace(os.sep, "/"))
    return files


manifest = {"rules": {}, "steal": [], "block": [], "general": []}

rules_dir = os.path.join(ROOT, "rules")
if os.path.isdir(rules_dir):
    for dog in sorted(os.listdir(rules_dir)):
        dog_path = os.path.join(rules_dir, dog)
        if os.path.isdir(dog_path):
            manifest["rules"][dog] = list_videos(dog_path)

for category in ("steal", "block", "general"):
    manifest[category] = list_videos(os.path.join(ROOT, category))

os.makedirs(ROOT, exist_ok=True)
out_path = os.path.join(ROOT, "manifest.js")
with open(out_path, "w") as f:
    f.write("// AUTO-GENERATED by scripts/gen-video-manifest.py - do not edit by hand.\n")
    f.write("window.VIDEO_MANIFEST = ")
    f.write(json.dumps(manifest, indent=2))
    f.write(";\n")

rule_count = sum(len(v) for v in manifest["rules"].values())
print(
    f"Wrote {out_path}: {rule_count} rule clips, "
    f"{len(manifest['steal'])} steal, {len(manifest['block'])} block, "
    f"{len(manifest['general'])} general"
)
